<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ResetZdoCounterTests.cs" />
    <Compile Include="../UpgradeWorld/ResetZdoCounter.cs" />
    <Reference Include="assembly_valheim" HintPath="../../Libs/assembly_valheim.dll" />
    <Reference Include="0Harmony" HintPath="../../Libs/0Harmony.dll" />
  </ItemGroup>
</Project>
